from .grub import install_grub
from .systemd_boot import install_systemd_boot
from .syslinux import install_syslinux
from .refind import install_refind
from .lilo import install_lilo
from .efistub import install_efistub
from .clover_efi import install_clover_efi
from .elilo import install_elilo
from .bootloader_setup import BootloaderSetup
