from .gnome import install_gnome
from .kde_plasma import install_kde_plasma
from .xfce import install_xfce
from .lxde import install_lxde
from .lxqt import install_lxqt
from .cinnamon import install_cinnamon
from .mate import install_mate
from .budgie import install_budgie
from .deepin import install_deepin
from .enlightenment import install_enlightenment
from .desktop_environment_setup import DesktopEnvironmentSetup
